## Loops

In [1]:
#i want to do teh same work again and again. use loops

In [ ]:
#print numbers 1-5
print(1)
print(2)
print(3)
print(4)
print(5)
#print 1-100. not gonna write it again anf again

In [2]:
#print your name five times
print('amitabh')
print('amitabh')
print('amitabh')
print('amitabh')
print('amitabh')

amitabh
amitabh
amitabh
amitabh
amitabh


In [7]:
class_age = 'medium'
if class_age=='old': 
    i=0
    while i<5:
        i+=1
        print('amitabh')
else:
    print('ritikh')

ritikh


In [11]:
for i in range(10):
    if i%2==1:
        print(i)

1
3
5
7
9


In [2]:
#lets try a loop. p.s. this is a comment. anything after a hash doesnt mean anything
for i in range(5):
    print('amitabh')

amitabh
amitabh
amitabh
amitabh
amitabh


In [4]:
for i in range(5): #show xrange
    print("1")

0
1
2
3
4


https://stackoverflow.com/questions/94935/what-is-the-difference-between-range-and-xrange-functions-in-python-2-x

In [5]:
for i in range(5): #show xrange
    print(i)

0
1
2
3
4


In [6]:
range(5) #command line. why does it start with zero? computers' counting starts with zero. REMMEBER!!!!

range(0, 5)

In [8]:
#lets use something better
for i in range(5):
    print(i, i+1)

0 1
1 2
2 3
3 4
4 5


In [9]:
#lets make a matrix
for i in range(5):
    print(i+0, i+1, i+2, i+3, i+4) #lets use a loop here as well

0 1 2 3 4
1 2 3 4 5
2 3 4 5 6
3 4 5 6 7
4 5 6 7 8


## Nested loops
If else can be nested. For loops can be nested as well.

In [10]:
for i in range(5):
    for j in range(5): #+[0,1,2,3,4] is basically range
        print(i+j)
#hmmm.... somethings not quite right. NEWLINE!

0
1
2
3
4
1
2
3
4
5
2
3
4
5
6
3
4
5
6
7
4
5
6
7
8


In [11]:
#what is newline?
#its a character just like 'h', 'e', 'l', 'l', 'o'. Its a special escape sequence. Escape sequencecs begin with backslash \
print('\n')

In [12]:
print('aa\naa')

aa
aa


In [14]:
#coming back o the problem. where hould the newline go?
for i in range(5):
    for j in range(5):
        print(i+j, )
    print('\n')

0
1
2
3
4


1
2
3
4
5


2
3
4
5
6


3
4
5
6
7


4
5
6
7
8




In [ ]:
#hmmmm... new line helps but what about being in the same line. print will go to the next line.

# Lists

In [12]:
print([1,2,3,4])

[1, 2, 3, 4]


In [13]:
a=[] #empty list

In [14]:
a.append(1)
print(a)
a.append(2)
print(a)
a.append(3000)
print(a)
# a.append(2) #repetition
# print(a)

[1]
[1, 2]
[1, 2, 3000]


In [16]:
#coming back to the problem. where hould the newline go?
for i in range(5):
    line_list=[]
    for j in range(5):
#         print(i+j, )
        line_list.append(i+j)
    print(line_list, '\n')

[0, 1, 2, 3, 4] 

[1, 2, 3, 4, 5] 

[2, 3, 4, 5, 6] 

[3, 4, 5, 6, 7] 

[4, 5, 6, 7, 8] 



# 1D list vs 2D list

In [ ]:
#we can do linear algebra with matrices!!

In [16]:
l=[[1,2,3], [3,4,5], [5,6,7]]
#what if the shape isnt constant?
l=[[1,2,3],[1,2],[1]] 
l

[[1, 2, 3], [1, 2], [1]]

https://stackoverflow.com/questions/43711836/an-array-of-linked-list-in-c
and this is just teh definition, you still have to populate it with teh integers :'(

In [19]:
matrix=[]
for i in range(5):
    line_list=[]
    for j in range(5):
        line_list.append(i+j)
    matrix.append(line_list)
#     print(line_list, '\n')
print(matrix) #needs some formatting suring printing tho. but its such a powerful tool now!
matrix[3][2]

[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]


5

In [5]:
#add two matrices
import numpy as np
l=np.arange(9).reshape(3,3)
print(l)
r=np.arange(9,18).reshape(3,3)
print(r)
print(l+r)
print(l*r)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 9 11 13]
 [15 17 19]
 [21 23 25]]
[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


https://www.programmingsimplified.com/c-program-add-matrices

# 3D lists

In [ ]:
#3D FTW!!!
#what is a 3d matrix.
#list of list of list

In [ ]:
#list     1D
[1,2,3]

In [ ]:
#list of list       2D
[[] , [] , []]

In [ ]:
#list of list of list     3D
[[], [], []] becomes
[         [[], [], []]    ,    [[], [], []]    ,   [[], [], []]         ]

In [20]:
matrix_3d = []
for k in range(3):
    matrix=[]
    for i in range(5):
        line_list=[]
        for j in range(5):
            line_list.append(i+j)
        matrix.append(line_list)
#     print(matrix)
    matrix_3d.append(matrix)
print(matrix_3d)

[[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], [[0, 1, 2, 3, 4], [1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], [[0, 1, 2, 3, 4], [1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]]


In [21]:
from pprint import pprint #pip install. lets dew it!

pprint(matrix_3d)

[[[0, 1, 2, 3, 4],
  [1, 2, 3, 4, 5],
  [2, 3, 4, 5, 6],
  [3, 4, 5, 6, 7],
  [4, 5, 6, 7, 8]],
 [[0, 1, 2, 3, 4],
  [1, 2, 3, 4, 5],
  [2, 3, 4, 5, 6],
  [3, 4, 5, 6, 7],
  [4, 5, 6, 7, 8]],
 [[0, 1, 2, 3, 4],
  [1, 2, 3, 4, 5],
  [2, 3, 4, 5, 6],
  [3, 4, 5, 6, 7],
  [4, 5, 6, 7, 8]]]


pip install numpy
https://youtu.be/U93tVa6rwpA?t=47

# nD matrix
https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html

In [23]:
import numpy
x = numpy.array([[1, 2, 3], [4, 5, 6]], numpy.int32)
type(x)
x.shape
x.dtype

numpy.ndarray

In [24]:
[1,2,3,4]*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [25]:
numpy.array([1, 2, 3, 4])+1

array([2, 3, 4, 5])

In [26]:
numpy.array([1, 2, 3, 4])**2

array([ 1,  4,  9, 16])

In [27]:
numpy.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [29]:
numpy.zeros((3,3,3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [31]:
numpy.full((2, 2), 10)*2

array([[20, 20],
       [20, 20]])

### transpose

In [32]:
import numpy as np #still works as nm ny 

In [36]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
np.transpose(x)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])